config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blogs do
    resources :comments
  end

  resources :users
  root "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blogs, dependent: :destroy
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_blog
  def current_blog
    @current_blog = Blog.find(params[:id])
  end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController



	def index
		@blogs = Blog.all
	end

	def new
		@blog = Blog.new
	end

	def create
		blog = Blog.new(blog_params)
    blog.user_id = current_user.id
		if blog.save
			redirect_to "/"
		else
			render "blogs/new"
		end
	end

	def show
		# @blog = Blog.find(params[:id])
		current_blog
	end


	def edit
		current_blog
	end

	def update
		blog = Blog.find(params[:id])
		if blog.update(blog_params)
			redirect_to "/"
		else
			render "blogs/#{blog.id}/edit"
		end
	end

	def destroy
		blog = Blog.find(params[:id])
		if blog.destroy
			redirect_to "/"

		end
	end


private
def blog_params
	params.require(:blog).permit(:title, :content, :user_id)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def list
	@comments = Comment.all
	# @blog = Blog.find(params[:blog_id])
end

def create
	@blog = Blog.find(params[:blog_id])
	@comment = current_user.comments.new(comment_params)
	@comment.blog = @blog
	if (@comment.save)
		redirect_to "/"
	else
		redirect_to "/blogs/#{params[:blog_id]}"
	end

end

def edit
		@blog = Blog.find(params[:blog_id])
		@comment = Comment.find(params[:id])

	end

def update
		comment = Comment.find(params[:id])
		if comment.update(comment_params)
			redirect_to "/"
		else
			render "blogs/#{blog.id}/edit"
		end
	end

private

def comment_params
	params.require(:comment).permit(:content, :blog_id, :user_id)
end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :fname,
                                  :lname,
                                  :username,
                                  :email,
                                  :password,
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :fname,
                                  :lname,
                                  :username,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    # @user = User.find(params[:id])
  end

  def show
    @blogs = Blog.all
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<h1>I don't need to edit this</h1>

app/views/blogs/index.html.erb
<h1>Sup <%if user_signed_in?%><%=current_user.username%>
  <%else%>you should like totally sign in bro<%end%></h1>

<div class = 'wrapper'>
<%@blogs.all.reverse.each do |b|%>
<div class = 'blog'>
<div class='title'><a href="/blogs/<%=b.id%>"><%=b.title%></a></div>
<div><%=b.content%></div>
<div>Posted by: <%=b.user.username%></div>
<div>Comments: <%b.comments.each do |c|%>
      <br>
      <%=c.user.username%>:
      <%=c.content%>
      <%end%>
</div>
</div>
<%end%>
</div>

app/views/blogs/new.html.erb
<!-- #<h3>Create a new Blog:</h3> -->
<div class='newBlog'><%=form_for @blog do |f|%>
<div id='newTitle'>Title: </div> <div><%=f.text_field :title, class: "text_title"%></div>
<div id='newContent'>Content: </div><div><%=f.text_area :content, class: "text_content"%></div>
<%= f.submit %>
<%end%></div>

app/views/blogs/show.html.erb
<div>
  <div class='blog'>
    <div class='title'><%= current_blog.title%></div>
    <div class='content'><%=current_blog.content%></div>
  </div>
  <%if user_signed_in?%>
  <%=form_for ([current_blog, current_blog.comments.build])  do |f|%>
  <div>Content: <%=f.text_area :content%></div>
  <%= f.submit %>
  <%end%>
  <%if current_user.id == current_blog.user_id%>
  <%=link_to "Edit", "/blogs/#{current_blog.id}/edit"%>
  <%= link_to "Delete Blog", blog_path, method: :delete, data: {confirm: 'Are You Sure about that?'}%>
  <%end%>
  <%end%>
</div>
<%= link_to "back",:back%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class='navbar'>
  <%if user_signed_in?%>
  <li><%= link_to "Home", root_path%></li>
  <li><%= link_to "New Blog", new_blog_path%></li>
  <li><%= link_to "Users", users_path%></li>
  <li><%= link_to "Edit Profile", edit_user_registration_path%></li>
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
  <%else%>
  <li><%=link_to "Sign In", user_session_path %></li>
  <%end%>
</nav>
<%if user_signed_in?%>
<div class="login">
  Logged in as: <%=current_user.username%>
</div>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%@users.each do |d|%>

<div class='users'><a href='/users/<%=d.id%>'><%=d.username%></a></div>
<%end%>

app/views/users/show.html.erb
<%if @user.username.last == "s"%>
<div class = 'show_username'><h1><%= @user.username%>' blog posts:</h1></div>
<%else%>
<div class = 'show_username'><h1><%= @user.username%>'s blog posts</h1></div>
<%end%>

<%if @user.blogs.count == 0%>
<h2 class='error'>Uh Oh! This user hasn't made any posts yet!</h2>
<%else%>
<%@user.blogs.reverse.each do |b|%>
<div class = 'blog'>
<div class='title'><a href="/blogs/<%=b.id%>"><%=b.title%></a></div>
<div>Posted by: <%=b.user.username%></div>
<div><%=b.content%></div>
</div>
<%end%>
<%end%>